name: Valgrind

on:
  workflow_dispatch:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master
  release:
    types:
      - published

env:
  BUILD_TYPE: Debug

jobs:
  valgrind:
    permissions:
      actions: read
      contents: read

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
           - name: Ubuntu GCC
             os: ubuntu-24.04
             compiler: gcc-13
             compilercxx: g++-13
           - name: Ubuntu Clang
             os: ubuntu-24.04
             compiler: clang
             compilercxx: clang++

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Restore vcpkg cache
      id: vcpkg-cache
      uses: TAServers/vcpkg-cache@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prefix: ${{ matrix.os }}_${{ matrix.compilercxx }}_valgrind_vcpkg

    - name: Configure CMake ${{ matrix.os }}-${{ matrix.compilercxx }}
      env:
        VCPKG_FEATURE_FLAGS: "binarycaching" # Possibly redundant, but explicitly sets the binary caching feature flag
        VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.compilercxx }}
      run: |
        cmake -B ${{github.workspace}}/build        \
            -DCRYPTOMATTE_API_DETERMINE_MAIN_PROJECT=OFF \
            -DCRYPTOMATTE_API_USE_VCPKG=ON         \
            -DCRYPTOMATTE_API_BUILD_TESTS=ON       \
            -DCRYPTOMATTE_API_EXTENDED_WARNINGS=ON

    - name: Build ${{ matrix.os }}-${{ matrix.compilercxx }}
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.compilercxx }}
      run: |
          cmake --build ${{github.workspace}}/build \
            --config ${{env.BUILD_TYPE}} \
            --parallel $(getconf _NPROCESSORS_ONLN || sysctl -n hw.ncpu || echo %NUMBER_OF_PROCESSORS%)
      
    - name: Run Valgrind
      working-directory: ${{github.workspace}}/build/test
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./cryptomatte_api_test
      continue-on-error: false